### PR TITLE
Finished BaseCost and LinearCost classes with tests.

### PR DESCRIPTION
**Pull request by gavin-hyl**
- **Finished BaseCost and LinearCost classes. Contains several CMake issues.**
- **Included CMakeLists.**

### CODE REVIEW

**Comment by Zolkin1** [comment]
@gavin-hyl it's looking good. I made some changes. Please pull the new code and make sure it runs/that you are ok with all the changes. when you are good with the changes I'll merge it in!

**Comment by gavin-hyl** [comment]
Just pulled. My catch2 setup had some minor problems, but its all fixed now.

**Comment by Zolkin1** [comment]
Looks like you removed the `linear_cost.cpp` file, which is fine, but I get a Cmake error saying I can't find that file when I try to run the tests because it is still being referenced in the Cmake file in the `costs` folder. Do you get the same error?

**Comment by gavin-hyl** [comment]
Apologies for not checking last time. I removed the file from the cmake and specified the target language, should be able to run now.

**Review by Zolkin1 — APPROVED** [review]
lgtm

**Pull request merged**
